### ISSUE TITLE
placement.lua "invalid object"

### ISSUE THREAD

**Issue by stevenroose** [Drauthius/awesome-sharedtags#3] opened 2018-11-06 15:18 UTC
Yesterday I installed this plugin. (It's awesome, btw!!)

Today I got an error message `an unexpected error occurred: [...]/awful/placement.lua: 119: [...?] invalid object`

It's one of those red popups that go away when you click them (to try and select the text, f.e. :| ), so I don't remember it fully.

It happened when I move a fullscreen (Firefox) window from my larger external monitor to my smaller laptop monitor and back. But it's not reliably reproducable..

**Comment by Drauthius** [comment] 2018-11-07 21:20
This plugin doesn't use the placement library directly, so I can't really say what's causing the error.

Which version of awesome are you using? Does it happen when you move the whole tag to another monitor, or when you move the window to another tag?

**Comment by stevenroose** [comment] 2018-11-08 13:35
When I move the tag to another monitor.

I also get the error consistently when I plug out a monitor and then go to a tag that was on the other monitor. The maximized windows will not be shown (even though the monitor is gone in xrandr as well), and when I unmax it, I get the error, remaxing bring the window in view.

**Comment by stevenroose** [comment] 2018-11-08 13:35
It seems that maximized windows are not correctly moved when tag is moved to another monitor due to a monitor disconnecting.

**Comment by Drauthius** [comment] 2018-11-13 11:20
I could (sort of) reproduce the problem you've seen. The error seems to come from within _awesome_, and seems to have been fixed in the master branch. But... even if the error has gone away, a maximized window isn't maximized correctly when a screen is unplugged and the tag is moved. I'm not sure why that is, and the things I've tried to do to get it to maximize properly haven't worked out. It seems like a maximized layout (instead of maximizing the program) doesn't have this problem.

So I think your best bet is to use a maximized layout instead, or try creating an issue in the _awesome_ project: https://github.com/awesomeWM/awesome

**Comment by stevenroose** [comment] 2018-11-13 13:50
@Drauthius what is a maximized layout?  I use the default ones usually..

**Comment by Drauthius** [comment] 2018-11-13 19:39
The maximized layout makes all the windows on that tag maximized. It should be part of the standard list of layouts that is cycled through when you press ModKey + Space. You can set it as the default for tags by adding `layout = awful.layout.suit.max` to your configuration when creating the tag list (as the example shows).

This is how I have my second tag set up (the one I called "www"). I then have a rule which places Firefox on that tag, but doesn't make it maximized since the tag layout will do that for me.

I'm not sure if this setup will work for you, but you could give it a try.

**Comment by stevenroose** [comment] 2018-11-13 20:06
Hmm, well my workspace is a bit more complex. I have several tags with different layouts that hold a browser window either maximized or in a tile. But well, at least you're aware of it. I can just remaximize them when I unplug the screen :) Thanks.

**Closed as completed** 2018-11-16 13:22 UTC
